development:
  adapter: postgresql
  encoding: unicode
  database: internetfriendsyay_development
  pool: 5
  username: <%= ENV['user'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: internetfriendsyay_test
  pool: 5
  username: <%= ENV['user'] %>
  password:
