default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: internetfriendsyay_development
  pool: 5
  username: <%= ENV['user'] %>
  password:

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: internetfriendsyay_test
  pool: 5
  username: <%= ENV['user'] %>
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: internetfriendsyay_development
  pool: 5
  username: <%= ENV['user'] %>
  password:
